### ISSUE TITLE
NuGet packages - message with JavaScript libraries "incompatible: use Library Manager instead"

### ISSUE THREAD

**Issue by christiannagel** [aspnet/LibraryManager#114]
Creating an ASP.NET Core project, and trying to add a script library from the NuGet server (NuGet PAckage Manager), this information is shown:
Incompatible: Use Library Manager instead

Previously it was shown to use Bower instead. Using Visual Studio 2017 15.7.3, and the Library Manager is not yet available, I would expect to still see the Bower message with a link to the Bower tools in Visual Studio.

Thanks,
Christian

**Comment by jodavis** [comment]
This will work again in 15.8 when Library Manager is added back in. This was a bad oversight, but it's not something we will service 15.7 for.
