### ISSUE TITLE
LibMan UI command entries should be disabled if there is another operation in progress

### ISSUE THREAD

**Issue by raquelsa** [aspnet/LibraryManager#118]
### Functional impact
We might run into conflicts if there are multiple libman tasks going on at the same time.  

### Minimal repro steps
1. Trigger restore onSave 
2. Select Clean from libman.json Context Menu UI. 

### Expected result
We should have only one operation at a time (Restore Client-side libraries from solution context menu is considered one operation)

**Comment by justcla** [comment]
Fixed in PR #192
