### ISSUE TITLE
Delete empty folders after a clean operation

### ISSUE THREAD

**Issue by raquelsa** [aspnet/LibraryManager#119]
### Functional impact
Currently only the immediate parent of a deleted library is also deleted if empty. We need to delete all folders (if empty) up the chain until working directory.

**Comment by justcla** [comment]
Ensure we update the docs when this fix is rolled out.

"Delete library files" section says:

> To prevent unintentional removal of non-library files, the clean operation doesn't delete whole directories. It only removes files that were included in the previous restore.

**Comment by justcla** [comment]
My bad. That statement is about not deleting directories with other files. Closing issue.
