### ISSUE TITLE
Improve error message when cleaning libraries twice

### ISSUE THREAD

**Issue by raquelsa** [aspnet/LibraryManager#121]
### Functional impact
If there are no libraries to clean, The Clean operation still outputs "libraries were successfully deleted". 
We should return "AllUpToDate" status when no deletions occurred and provide a better error message.

**Comment by jimmylewis** [comment]
The "All up to date" is confusing after a clean because the files are all missing, not up to date.  It is more understandable to keep the messaging as it already exists, so that it clearly affects the state of the files (not) on disk.
