### ISSUE TITLE
Stop operation not working as expected for task management

### ISSUE THREAD

**Issue by YangLyu89** [aspnet/LibraryManager#124]
### Minimal repro steps
1. Open a .NET core project with libman.json
2. right click on libman.json, choose restore client-side libraries
3. click the task management on the bottom, and stop the operation

### Expected result
The operation should be displayed something as cancelled

### Actual result
It displayed as completed

**Comment by raquelsa** [comment]
The operation is cancelled but we are writing the wrong error message.

**Comment by raquelsa** [comment]
Fixed in #139
