### ISSUE TITLE
Update the Issue template for this repo to be more relevant

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/LibraryManager#129]
Update the Issue template for this repo to be more relevant

The current template is as below has example steps based on SQL connection issues. 

/cc @justcla @jodavis 

> ![image](https://user-images.githubusercontent.com/1521254/41258551-67bfaa24-6d85-11e8-8fe2-d7f07e51ad7e.png)

**Comment by RobJohnston** [comment]
Here's a suggestion... simply copy the files from https://github.com/aspnet/Universe/tree/master/.github.  There are templates for both a bug report **and** a feature request.

There is also a pull request template in there that matches the format mentioned in https://github.com/aspnet/LibraryManager/blob/main/.github/CONTRIBUTING.md

Let me know and I can create a PR.
