### ISSUE TITLE
LibMan apparently works on invalid JSON file

### ISSUE THREAD

**Issue by jimmylewis** [aspnet/LibraryManager#136]
### Functional impact
*Does the bug result in any actual functional issue, if so, what?*  
No, it's just surprising that it works at all.  I would expect it to fail if the file is not valid JSON.

### Minimal repro steps
*What is the smallest, simplest set of steps to reproduce the issue. If needed, provide a project that demonstrates the issue.*  

1. Paste the following into libman.json:

```
{
  "version": "1.0",
  "defaultProvider": "cdnjs",
  "libraries": [
    {
      "library": "jquery@3.3.1",
      "destination": "lib/jquery",
      "files": [
        "jquery.js",
      ]
    }
  ]
}
```

Note the comma after `"jquery.js"` which is not followed by another item in the array.

### Expected result
LibMan would fail saying the file isn't valid.

### Actual result
LibMan does what it would if the comma wasn't there.

**Comment by prafullbhosale** [comment]
It works even with below: 

```js
{
  "libraries": [
    {
      "provider": "cdnjs",
      "library": "mori@0.3.2",
      "destination": "Scripts/mori",
      "files": [
        "mori.js",
        "mori.min.js"
      ]
    }
  ],
  "version": "1.2",
  "version": "1.0",
  "libraries": [
    {
      "provider": "cdnjs",
      "library": "jquery-placeholder@2.3.1",
      "destination": "Scripts/jqueryplaceholder",
      "files": [
      ]
    }
  ],
}
```

Related #143

**Comment by jimmylewis** [comment]
Honestly, this doesn't seem very severe.  It's also a well-known behavior of JSON.NET when using DeserializeObject.  The JSON editor in VS will flag the syntax issue, I think that's good enough.
