### ISSUE TITLE
[CLI] "libman clean" command deletes only deepest empty folders

### ISSUE THREAD

**Issue by alexgav** [aspnet/LibraryManager#138]
### Functional impact
*Some empty folders are left behind. Not sure if that's by design*  

### Minimal repro steps

1. Install jquery@3.3.0 using cdnjs into wwwroot\script\jq
2. Execute 

```
libman clean
```

### Expected result
Honestly, not sure. There is a warning in the command output that empty folders will be deleted. What I am seeing is that "jq" is deleted but not "script". Should we delete empty folders all the way up to the root of the project?

### Actual result
Only deepest empty folder is deleted, i.e. "jq"

### Further technical details
*This could be by design - a bit confusing though that we delete some empty folders but not all*

**Comment by raquelsa** [comment]
Same as #119

**Comment by jodavis** [comment]
This is a duplicate.
