### ISSUE TITLE
UI is blocked till restore operation is complete

### ISSUE THREAD

**Issue by bhsubra** [aspnet/LibraryManager#141]
### Functional impact
UI is blocked till restore is complete when the library is too big e.g: moment in UnPkg

### Minimal repro steps
- Bring up the dialog to add client side library
- Select UnPkg provider
- Specify moment@2.22.2 for library
- Select install all library files
- Install
- The dialog remains open until restore is complete which takes a lot of time
- If you hit close manually, option to add client side library is not available

### Expected result
The dialog should close and allow user to add more client side libraries

### Actual result
 The dialog remains open until restore is complete which takes a lot of time. If you hit close manually, option to add client side library is not available

**Comment by jimmylewis** [comment]
The dialog is no longer blocking, and the IDE is responsive.  The restore operation does block re-entry into the wizard, but that's similar to build blocking certain operations as well.  Marking this issue as fixed.
