### ISSUE TITLE
[CLI] libman install doesn't produce any output for quite a while when installing large libraries using unpkg

### ISSUE THREAD

**Issue by alexgav** [aspnet/LibraryManager#142]
### Functional impact
*Command appears hung. It's a feature request though.*  

### Minimal repro steps

1. Install a large library (e.g. jquery) using unpkg provider by executing something like

```
libman install jquery@3.3.0 -p cdnjs -d wwwroot\lib\jq
```

### Expected result
*Some sort of indication things are working/progressing*  

### Actual result
The command doesn't produce any output such as progress indication until all files of the library are downloaded. It appears hung. After a few seconds, all results come back at once. It would be nice to have progress indication. 

### Further technical details
*Maybe as the first step we could produce output like "installing library xxx..."*. Ideally we should putout "filexxx written to disk" for each file rather than all at once after the operation is completed. 

This is a pri 3 though.

**Comment by jimmylewis** [comment]
This has been resolved.  We now show output messages as we are downloading each file so progress is shown consistently throughout the operation.
