### ISSUE TITLE
[CLI] Running "libman restore" on a file with invalid provider id could produce a better message

### ISSUE THREAD

**Issue by alexgav** [aspnet/LibraryManager#144]
### Functional impact
*No functional impact, error could be better though*  

### Minimal repro steps

1. Add invalid provider to one of the libraries in libman json, e.g. "foo"
2. Execute

```
libman restore
```

### Expected result
Error message stating provider "foo" is not installed, like I would get for specifying it in "libman install" command

### Actual result
[LIB007]: The provider is undefined

### Further technical details
*This could be a limitation of the code outside of the CLI (probably is). Still, it would be nice to tell user which provider is invalid so they could search libman.json for that specific provider id*

**Comment by jodavis** [comment]
This is a really unhelpful error message, and should be fixed. (It's a little more helpful if the error message has a line number.)

**Comment by RobJohnston** [comment]
I don't think this is an issue anymore.  I'm getting the message, 

> [LIB001]: The "foo" provider could not be found

If I'm reading things correctly, this was fixed around line 44 of Extensions.cs in https://github.com/aspnet/LibraryManager/pull/266/commits/4519e1831ccdfaf78bdae80a3a07f1be63430133

**Comment by jimmylewis** [comment]
Thanks @RobJohnston for confirming
