### ISSUE TITLE
Add Client-Side Library dialog causes VS to show reload file dialog for libman.json 

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/LibraryManager#147]
### Functional impact
1. The user can no longer undo edits in the file due to the reload.
2. If the file had unsaved edits, those are lost after reload.

### Minimal repro steps
1. Open libman.json file in VS 
2. Right click a folder and select Add-> Client Side Library
3. Type any library name and click install. 

### Expected result
The libman.json file is updated with the new library (and shows the highlight on the left that indicates the portion that was edited.)
![image](https://user-images.githubusercontent.com/1521254/41261608-5266ee60-6d91-11e8-8ccb-de937b0ef128.png)

If libman.json was unsaved before installing the library, it would be good to confirm with the user to Save the file as part of the operation.

### Actual result
A reload file dialog is shown: 
![image](https://user-images.githubusercontent.com/1521254/41261651-8e645ee8-6d91-11e8-83b7-2dce887caacb.png)

**Comment by bhsubra** [comment]
Fixed via commit:
https://github.com/aspnet/LibraryManager/commit/38537f94ce2cbedac106828c63ad7b195f365958
