### ISSUE TITLE
only twitter-bootstrap is installed

### ISSUE THREAD

**Issue by aminsoraya** [aspnet/LibraryManager#160]
when i try to install bootstrap in library. after hit bootstrap . twitter-bootstrap was shown and installed and any other package cant be installed why?

**Comment by prafullbhosale** [comment]
This seems related to #120, 
The special mapping of `bootstrap` -> `twitter-bootstrap` is being removed as part of #167

**Comment by jodavis** [comment]
This should be fixed already. @YangLyu89, please verify and close.

**Comment by YangLyu89** [comment]
Verified. It now should not have bootstrap in completion option and twitter-bootstrap will be displayed instead.
