### ISSUE TITLE
6 warnings and 1 error

### ISSUE THREAD

**Issue by aminsoraya** [aspnet/LibraryManager#161]
![warning](https://user-images.githubusercontent.com/17019549/41360004-fc34ec2a-6f40-11e8-815e-9aa4cfc1398c.JPG)
![error](https://user-images.githubusercontent.com/17019549/41360131-41dd4a06-6f41-11e8-9811-df981efdf049.JPG)

I think these can  cause a serious problems and must be resolved as soon as possible but how????

**Comment by prafullbhosale** [comment]
@aminsoraya Could you provide more information on your environment? 
Visual Studio version: ?? 
.NET Core SDK version: ??  (You can run `dotnet --info` on a command prompt for this)

**Comment by aminsoraya** [comment]
those error  and warning was related to the test libman.cspro inside main projects . my VS and SDK are updated till now. I was removed the test project and re build the all project and all things works right

**Comment by RobJohnston** [comment]
Addressed, at least in part, in https://github.com/aspnet/LibraryManager/pull/563.

**Comment by jimmylewis** [comment]
Closing this as it's super old and the MAT dependency was removed a few years ago.
