### ISSUE TITLE
Autocomplete of 'jquerycarousel' becomes 'jquery_carousel' 

### ISSUE THREAD

**Issue by bhsubra** [aspnet/LibraryManager#163]
### Functional impact
Autocomplete of 'jquerycarousel' becomes 'jquery_carousel'  for unPkg provider

### Minimal repro steps
 -  Select Unpkg provider, type jquery and pause. The 2nd option in the drop down is 'jquerycarousel' select that with mouse
-   The text in the library text box is 'jquery_carousel' instead of 'jquerycarousel'

### Expected result
Expected the text to be jquerycarousel

### Actual result
Actual text is jquery_carousel

I'm not sure if this is desired behavior or by design but we need to verify

**Comment by jodavis** [comment]
This could be related to https://github.com/aspnet/LibraryManager/issues/198

**Comment by alexgav** [comment]
Fixed with https://github.com/aspnet/LibraryManager/pull/290
