### ISSUE TITLE
Is this still only in VS previews?

### ISSUE THREAD

**Issue by los93sol** [aspnet/LibraryManager#173]
Apologies for posting this here, but I could not find any information about if this is supposed to be in release builds of VS or when it is expected to be released.

**Comment by D3MaxT** [comment]
As far is I know, yes. It was supposed to be released with 15.7, but wasn't. And right now it is present in 15.8 previews.

**Comment by jodavis** [comment]
Thanks @D3MaxT, you're correct. It was pulled from 15.7 before it shipped, but it's planned to ship with 15.8.
