### ISSUE TITLE
LibMan is not aware of the "Default Project" in the Package Manager Console

### ISSUE THREAD

**Issue by jodavis** [aspnet/LibraryManager#188]
### Functional impact
When using LibMan CLI commands in the Package Manager Console, it uses the current working directory, which appears to default to the solution root. 

### Minimal repro steps
PM> libman install jquery -d wwwroot/lib/jquery -p cdnjs
wwwroot/lib/jquery/core.js written to disk
wwwroot/lib/jquery/jquery.js written to disk
wwwroot/lib/jquery/jquery.min.js written to disk
wwwroot/lib/jquery/jquery.min.map written to disk
wwwroot/lib/jquery/jquery.slim.js written to disk
wwwroot/lib/jquery/jquery.slim.min.js written to disk
wwwroot/lib/jquery/jquery.slim.min.map written to disk
Installed library '(jquery@3.3.1, jquery)' to 'wwwroot/lib/jquery'

### Expected result
jQuery files are added to the project

### Actual result
jQuery files are written somewhere, but there's no indication where they went. Some searching will discover they were added relative to the solution folder.

**Comment by jodavis** [comment]
This is not a supported scenario right now, but we could consider supporting it better if there was demand for it.

**Comment by jimmylewis** [comment]
Closing due to lack of 👍.  This seems pretty edge case to be using the CLI from within VS, instead of the VS integration.
