### ISSUE TITLE
Output window should be open when there are LibMan tasks running

### ISSUE THREAD

**Issue by raquelsa** [aspnet/LibraryManager#193]
### Functional impact
User might not notice that LibMan operations have started if Output window is not open with LibMan option selected

### Expected result
We should open output window (with LibMan option selected) when there are tasks running for LibMan operations triggered by the UI.

**Comment by jodavis** [comment]
We need to spec this behavior. Popping the output window frequently can be annoying.

**Comment by jimmylewis** [comment]
Closing as not-planned.  The current behavior matches how most other Output window sources behave.
