### ISSUE TITLE
[Add Files Dialog] Tabbing through UI inserts first item in dropdown into location.

### ISSUE THREAD

**Issue by justcla** [aspnet/LibraryManager#198]
Happens in both library and location inputs where IntelliSense is available.

**Comment by jimmylewis** [comment]
This should not trigger a completion dropdown until the user types a character in the box.

**Comment by jodavis** [comment]
https://github.com/aspnet/LibraryManager/issues/163 might be related to this.

**Comment by bhsubra** [comment]
Fixed via https://github.com/aspnet/LibraryManager/commit/05e8ea29eb10fd0e7c90588d9f4d249a9399d331
