### ISSUE TITLE
[Add Files Dialog] Detect if launched from project root and use (wwwroot)/lib as prefix for Specified Location

### ISSUE THREAD

**Issue by justcla** [aspnet/LibraryManager#200]
- If launched from a folder that is NOT the project root, the folder launch from is the default prefix.
- If launch from the project root, the default will be:
  - wwwroot/lib - if a wwwroot directory exists at the project root,
  - lib - otherwise

**Comment by jodavis** [comment]
This is part of a larger design change that isn't finished yet.
