### ISSUE TITLE
[Add Files Dialog] Target location needs to append library name to current folder

### ISSUE THREAD

**Issue by justcla** [aspnet/LibraryManager#201]
When the user tabs out of the Library field, if there is a valid library (ie. files exist in the Files box), reset the Specified location field to a new value that is: [LaunchFolder]/[LibraryName]
(where [LaunchFolder] might be (wwwroot)/lib if launched from the Project root. See #200)

Keep a track of the last suggested location.

Before resetting to a new suggested location, first check if the current value in the location field is the same as the last suggestion. If it is different, do make reset the location field.
If the value is the same as the last suggestion, replace it with the new suggested location (and store that as the new last-suggested-location value).

**Comment by jodavis** [comment]
This is part of a larger design change that isn't finished yet.

**Comment by justcla** [comment]
Not working correctly in all cases.

Need to check logic for when to reset user's manually changed target location.

Logic should be:
            // initialSuggestion(lastSuggestion) = (init - launch folder or wwwroot/lib)

            // when a new library is chosen
            // if (current value in target location == the LastSuggestion) {
                // newSuggestion = (generate new suggestion: [LaunchFolder]/[libraryName]
                // update the LastSuggegstion to = newSuggestion
            // }
        }

**Comment by YangLyu89** [comment]
resolved the issue Justin mentioned.
