### ISSUE TITLE
[Add Files Dialog] [UnPkg] Search for libraries should be contains, not startsWith

### ISSUE THREAD

**Issue by justcla** [aspnet/LibraryManager#214]
I have a feeling this is already working.
Check all providers.
Works in CDNJS. Broken in UnPgk.

To reproduce:

- Add Library Files
- Provider: UnPgk
- Library search: "bootstrap"

Notice that the "twitter-bootstrap" libraries do not show.

**Comment by justcla** [comment]
This is an issue for UnPgk provider. CDNJS provider is already doing "contains-with" search.

**Comment by justcla** [comment]
To reproduce:
- Add Library Files
- Provider: UnPgk
- Library search: "bootstrap"

Notice that the "twitter-bootstrap" libraries do not show.

**Comment by jimmylewis** [comment]
"twitter-bootstrap" is a Cdnjs-specific name.  On NPM-based providers, it's just bootstrap.

That said, NPM-based providers now rely on NPM's default search, which goes by partial matches on package names and metadata, so this is fixed anyway.
