### ISSUE TITLE
[Add Library Dialog] Typing is slow/blocked in Library field of the dialog

### ISSUE THREAD

**Issue by alexgav** [aspnet/LibraryManager#229]
### Functional impact
*I can't type fast in the Library field of the UI*  

### Minimal repro steps

1. Open Add Client-Side Library dialog
2. Try typing fast in the Library field

### Expected result
*I should be able to type as fast as I can, even if completion can't keep up*  

### Actual result
*Typing is slow/jerky. Not sure if it's better on release builds?*

### Further technical details
*We shouldn't block user typing even if completion can't keep up.*

**Comment by jimmylewis** [comment]
I believe this was fixed a while ago to move the library look up requests off the main thread (probably #516).  I can't hit this anymore.
