### ISSUE TITLE
[CLI][unpkg] Error installing from unpkg: Index was outside the bounds of the array

### ISSUE THREAD

**Issue by justcla** [aspnet/LibraryManager#231]
C:\Projects\LibManCLITest>libman install jquery
DefaultProvider [cdnjs]: unpkg
Destination [lib\jquery]:

Index was outside the bounds of the array.

Might be related to issue #157

**Comment by raquelsa** [comment]
This might be fixed with the validation work that was checked in yesterday. @justcla , can you please verify?

**Comment by justcla** [comment]
This is not fixed by the validation work.
But there is now a new error.

**Comment by justcla** [comment]
Closing this ticket as it's a dupe of #157
