### ISSUE TITLE
It's hard to know where local machine cache is stored.

### ISSUE THREAD

**Issue by justcla** [aspnet/LibraryManager#234]
Please print the location of the local cache during a Cache List and Cache Clean

**Comment by ygoe** [comment]
Wait, there is a local cache? I think I don't have one. Because LibMan fails the entire build every other time due to network-related errors ("unpkg" can't resolve a package, and such). This wouldn't happen if there was a properly working local cache, like there is for NuGet.

**Comment by Roman-Tarasiuk** [comment]
> Wait, there is a local cache? I think I don't have one. Because LibMan fails the entire build every other time due to network-related errors ("unpkg" can't resolve a package, and such). This wouldn't happen if there was a properly working local cache, like there is for NuGet.

@ygoe, Maybe your problem will be resolved with https://github.com/aspnet/LibraryManager/pull/466. (See also link to the https://github.com/aspnet/LibraryManager/issues/399#issuecomment-472760343 – in my Windows PCs it has local cache.)

**Comment by Roman-Tarasiuk** [comment]
> Wait, there is a local cache? I think I don't have one. Because LibMan fails the entire build every other time due to network-related errors ("unpkg" can't resolve a package, and such). This wouldn't happen if there was a properly working local cache, like there is for NuGet.

@ygoe, Maybe your problem will be resolved with #466. (See also link to the #399 (comment) – in my Windows PCs it has local cache.)

**Comment by ygoe** [comment]
There's no proxy in my network, this can't be related.
