### ISSUE TITLE
[CLI] Error attempting to restore (after cache clean)

### ISSUE THREAD

**Issue by justcla** [aspnet/LibraryManager#241]
C:\Projects\LibManCLITesting>libman restore

Failed to restore "{twitter-bootstrap@2.0.0, cdnjs, lib\twitter-bootstrap}"
  - [LIB002]: The "twitter-bootstrap@2.0.0" library could not be resolved by the "cdnjs" provider

**Comment by jimmylewis** [comment]
I regularly do cache clean and then restore when testing changes, and haven't encountered this in recent memory.
