### ISSUE TITLE
Version completion doesn't work for Unpkg provider

### ISSUE THREAD

**Issue by YangLyu89** [aspnet/LibraryManager#272]
### Minimal repro steps
Open libman.json file
Adding a library, in the "library": filed, type something like "jquery@"

### Expected result
A list of available version displayed

### Actual result
Nothing displayed.

**Comment by alexgav** [comment]
This was fixed by Yang. Closing this bug. The current behavior of having to know to type "@" is not ideal, but we do have #394 to figure out better behavior.
