### ISSUE TITLE
Summary output of operations does not show libraries that are up-to-date

### ISSUE THREAD

**Issue by raquelsa** [aspnet/LibraryManager#287]
Summary of operations on the output window does not include status for uptodate libraries. It would be a clear message if we could state the status of libraries that are uptodate. E.g.: If there are 4 libraries being restored, and 3 of them are uptodate. The output message would look like: 

1 libraries restored in 6,61 seconds

Expected:
3 libraries are up to date
1 libraries restored in 6,61 seconds

**Comment by raquelsa** [comment]
PR #305 should fix that.

**Comment by jimmylewis** [comment]
We don't seem to say which ones were up to date, but we do print each library that was restored.  I think that's good enough on this scenario, the user is informed of each library that was installed (even if no changes were made).
