### ISSUE TITLE
libman.json reports errors for valid destination 

### ISSUE THREAD

**Issue by YangLyu89** [aspnet/LibraryManager#298]
### Minimal repro steps
Create a libman.json file as:
{
  "version": "1.0",
  "defaultProvider": "cdnjs",
  "libraries": [
    {
      "library": "jquery@3.3.1",
      "destination": "wwwroot\\lib\\jquery"
    }
  ]
}

### Expected result
No error reported

### Actual result
report warning for destination property

**Comment by jimmylewis** [comment]
The issue here is the slashes aren't escaped.  JSON strings must escape `\` as `\\`
