### ISSUE TITLE
LibMan package is not being initialized for projects with LibMan.json

### ISSUE THREAD

**Issue by raquelsa** [aspnet/LibraryManager#304]
Repro:
1. Open an existing project with LibMan.json file 
2. Right click the file

Result:
- The "Enable/Disable client side Libraries on build" is not visible because the package was not initialized

Workaround: right click the LibMan.json file and select "Client side libraries" which will initialize the package

**Comment by jodavis** [comment]
We should at least understand why this is happening.

**Comment by jodavis** [comment]
This is fixed in 15.7 Preview 2. There's new loading support that was not in the old build where this was tested.
