### ISSUE TITLE
Broken behavior when dealing with libraries containing an @ symbol

### ISSUE THREAD

**Issue by nickalbrecht** [aspnet/LibraryManager#329]
### Functional impact
Attempting to check for updates to something like SignalR results in breaking the library name

### Minimal repro steps
Set your libman.json file as follows
```
{
  "defaultProvider": "unpkg",
  "libraries": [
    {
      "library": "@aspnet/signalr@1.0.2",
      "files": [
        "dist/browser/signalr.js"
      ],
      "destination": "wwwroot/vendor/signalr"
    }
  ],
  "version": "1.0"
}
```

Then using the lightbulb quick action to try and check for updates to SignalR.

### Expected result
It should determine there are no updates available

### Actual result
You'll get the option to update to "Stable: 1.0.2" 
Clicking to do so will replace the entire library name from "@aspnet/signalr@1.0.2" to "1.0.2".

### Further technical details
I believe It's just parsing off of the first found `@` symbol, when it should be using the last one.

**Comment by jimmylewis** [comment]
This is working for me.  Feel free to reopen if you're still hitting it.
