### ISSUE TITLE
[Request] libman.json example snippet

### ISSUE THREAD

**Issue by NicoCG** [aspnet/LibraryManager#333]
Could someone kindly guide me on libman.json file to install libraries on visualstudio my current file looks like this.

```
{
  "version": "1.0",
  "defaultProvider": "cdnjs",
  "libraries": [
    {
      "library": "jquery@3.2.1",
      "destination": "wwwroot/js/lib",
      "files": [ "jquery.min.js" ]
    }
  ]
}
```

But I need it to install the following Latest libraries `booststrap`, `jquery`, `jquery.validate` and `jquery.validate.unobtrusive`

Can anyone share me there snippet to install the above please.

**Comment by nickalbrecht** [comment]
This isn't really an issue with LibMan. But to answer your question, go to `https://cdnjs.com/` and search for the libraries you want to use. Copy the library name from there to get the correct syntax LibMan needs and the version number for the most recent version (or whatever version you need), and you can start to flesh out your list of libraries. Also check out the README.md file on the repository for tips on how to use the intellisense to help with this as well.

Issues here are more meant for bugs you find with LibMan

**Comment by NicoCG** [comment]
Thanks @nickalbrecht
