### ISSUE TITLE
Can this be integrated or merged in with...

### ISSUE THREAD

**Issue by StingyJack** [aspnet/LibraryManager#337]
... the NuGet Package Manager UI? 

Its not the greatest UI, but I really don't want to have to use two package managers or two "file package installers", and I used to be able to add Newtonsoft.Json and jQuery and a host of other stuff in the same place at about the same time.   

Both tools are from MSFT, and from a user perspective, it makes sense to just merge them into a seamless experience.

**Comment by jodavis** [comment]
@justcla We should discuss whether we can work with NuGet to make our tooling story more consistent in Visual Studio.

**Comment by jimmylewis** [comment]
This is not on any roadmap, there's too many differences at this point to casually reconcile without making it an involved effort.
