### ISSUE TITLE
[CLI]: The cache list command should not list any providers that do not have any cached files. 

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/LibraryManager#347]
Currently the `libman cache list` command outputs is as below which includes providers that have no cached files. 

```
Cache contents:
---------------
unpkg:
    twitter-bootstrap
filesystem:
    (empty)
cdnjs:
    bootstrap
    jquery
    twitter-bootstrap
    underscore.js
```

It should not include any providers that do not have any cached files.

**Comment by RobJohnston** [comment]
Duplicate of https://github.com/aspnet/LibraryManager/issues/240.

**Comment by jimmylewis** [comment]
Closing duplicate
