### ISSUE TITLE
Code clean up: remove telemetry constants from non .vsix projects

### ISSUE THREAD

**Issue by raquelsa** [aspnet/LibraryManager#351]
src\libman\Contracts\Constants.cs:16:        public const string TelemetryNamespace = "webtools/librarymanager/";
src\LibraryManager.Build\Constants.cs:12:        public const string TelemetryNamespace = "webtools/librarymanager/";

**Comment by RobJohnston** [comment]
Can be closed, because both reference files were removed in https://github.com/aspnet/LibraryManager/pull/474/commits/cf0d636a139c24f129201f89195cf0b60d33051e on April 23, 2019.
