### ISSUE TITLE
Installing CLI Tool

### ISSUE THREAD

**Issue by djhaanpaa** [aspnet/LibraryManager#354]
### Functional impact
*Does the bug result in any actual functional issue, if so, what?*  
Not being able to use the libman cli tool

### Minimal repro steps
*What is the smallest, simplest set of steps to reproduce the issue. If needed, provide a project that demonstrates the issue.*  

1. Startup Mac OS X terminal
2. type in "dotnet tool install -g libman"

### Expected result
*What would you expect to happen if there wasn't a bug*  
Libman CLI tool is installed

### Actual result
*What is actually happening*  
error NU1101: Unable to find package libman. No packages exist with this id in source(s): /usr/local/share/dotnet/sdk/NuGetFallbackFolder, nuget.org
The tool package could not be restored.
Tool 'libman' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool

**Comment by joergjo** [comment]
Same error here on Windows 10 with SDK 2.1.400.

**Comment by justcla** [comment]
The LibMan CLI is now available on NuGet
[https://www.nuget.org/packages/Microsoft.Web.LibraryManager.Cli/](https://www.nuget.org/packages/Microsoft.Web.LibraryManager.Cli/)

The syntqax for installing LibMan is:

> `dotnet tool install -g Microsoft.Web.LibraryManager.Cli`
> 
> You can invoke the tool using the following command: libman
> Tool 'microsoft.web.librarymanager.cli' (version '1.0.163') was successfully installed.
> 

To uninstall LibMan, use the following command:

> `dotnet tool uninstall -g Microsoft.Web.LibraryManager.Cli`
> 
> Tool 'microsoft.web.librarymanager.cli' (version '1.0.163') was successfully uninstalled.

**Comment by justcla** [comment]
Here's an example:

![image](https://user-images.githubusercontent.com/17131343/44427855-8e180500-a547-11e8-870f-7807d717ff03.png)
