### ISSUE TITLE
Fix the logic to get the latest version

### ISSUE THREAD

**Issue by felipepessoto** [aspnet/LibraryManager#359]
### Functional impact
It downloads the incorrect latest version of some libraries.

### Minimal repro steps
libman install prism

### Expected result
Install prism 1.15.0, the version that is shown when I open the library url: https://cdnjs.com/libraries/prism or when calling the API, the object root has a **Version** property that should be considered, https://api.cdnjs.com/libraries/prism:
![image](https://user-images.githubusercontent.com/1336227/44548302-0b807880-a6f4-11e8-8c8c-391633e4865b.png)

### Actual result
It is installing the first version that it found in array: 9000.0.1.
https://github.com/aspnet/LibraryManager/blob/45474d37ed6977b744786e102c397b4f558a8096/src/LibraryManager/Providers/Cdnjs/CdnjsCatalog.cs#L194

### Further technical details
The CDNJS API has a property to flag the current version, so we should use it.
I'll try to send a fix via pull request and create a unit test to cover this scenario.

Could you assign to me?

**Comment by jodavis** [comment]
@fujiy thanks for identifying this and offering to fix it.

**Comment by felipepessoto** [comment]
@jodavis I'm having problem with AppVeyor, each time it runs, a different test fails, none of them related with my change. In my machine the tests are OK

**Comment by jimmylewis** [comment]
Thanks @felipepessoto for submitting the fix!
