### ISSUE TITLE
Uninstall of filesystem library fails in VS

### ISSUE THREAD

**Issue by scottaddie** [aspnet/LibraryManager#363]
### Functional impact
In Visual Studio, I'm unable to uninstall a library that's using the _filesystem_ provider.

### Minimal repro steps

1. Create a new ASP.NET Core Razor Pages app targeting .NET Core 2.1.
2. Add a *libman.json* file to the project root with the following contents:

```json
{
  "version": "1.0",
  "defaultProvider": "cdnjs",
  "libraries": [
    {
      "provider": "filesystem",
      "library": "C:\\tmp\\contosoCalendar",
      "files": [
        "calendar.js",
        "calendar.css"
      ],
      "destination": "wwwroot/lib/contosoCalendar/"
    }
  ]
}
```

3. With the *libman.json* file open in the editor, position the caret in the left margin. Click the light bulb icon that appears, and select the *Uninstall C:\\tmp\\contosoCalendar* option.
4. Notice that the object literal inside of *libman.json*'s `libraries` property is removed. The files in the project aren't removed.

### Expected result
The object literal inside of the `libraries` property of *libman.json* should be removed. The library files should be deleted from the configured location in the project.

### Actual result
The **Library Manager** feed of Visual Studio's **Output** window displays the following:

```console
Uninstall of library C:\\tmp\\contosoCalendar started...
Uninstall of library C:\\tmp\\contosoCalendar failed
Object reference not set to an instance of an object.
```

### Further technical details
* VS 2017 Enterprise v15.8.1
* .NET Core SDK v2.1.401
* LibMan CLI v1.0.163+g45474d37ed

**Comment by justcla** [comment]
Thanks Scott. We'll look into this.
