### ISSUE TITLE
There is not Microsoft.Web.LibraryInstaller.Contracts NuGet package.

### ISSUE THREAD

**Issue by jack128** [aspnet/LibraryManager#365]
### Functional impact
There is not Microsoft.Web.LibraryInstaller.Contracts NuGet package.

### Minimal repro steps
As [docs](https://github.com/aspnet/LibraryManager/wiki/Extensibility) says:

1. Make sure the Visual Studio SDK is installed and then create a new extensibility project by creating a VSIX Project.
2. Open Package Manager Console and execute Install-Package Microsoft.Web.LibraryInstaller.Contracts

### Expected result

Package should be installed

### Actual result
Error: Unable to find package 'Microsoft.Web.LibraryInstaller.Contracts'

### Further technical details
As you can see here https://www.nuget.org/packages?q=Microsoft.Web.LibraryInstaller.Contracts "0 packages returned for Microsoft.Web.LibraryInstaller.Contracts"

**Comment by justcla** [comment]
This page was old and referred to the initial prototype.

At this stage, there is no defined path for extending LibMan.
It's likely we will release one in the coming months.

**Comment by justcla** [comment]
I have removed the content from the Extensibility Wiki.
