### ISSUE TITLE
Configure LIBMAN for in order to use  SCSS 

### ISSUE THREAD

**Issue by elizad** [aspnet/LibraryManager#369]
*How can I configure Libman in order to be able to use SCSS instead CSS file and compile on browser LOAD?  *
 Any suggestions?

**Comment by justcla** [comment]
LibMan doesn't have anything to do with how files are compiled. The role of LibMan is to fetch files from external sources. If there are SCSS files you want to download, you can specify them in the libman.json and they will be restored on demand or on build (if enabled in the project file).
