### ISSUE TITLE
[CLI] libman init: accept defaults

### ISSUE THREAD

**Issue by scottaddie** [aspnet/LibraryManager#378]
I propose an enhancement to the `libman init` CLI command, such that a `-y` option is supported. By running `libman init -y`, all default settings are accepted and I'm no longer prompted for a DefaultProvider value. An example of where this is possible today is npm: `npm init -y`.

**Comment by justcla** [comment]
Great suggestion, Scott. Thanks. We will look to add something like this in a future release.
