### ISSUE TITLE
[File System Provider] Add folder support on URLs

### ISSUE THREAD

**Issue by aureole82** [aspnet/LibraryManager#379]
### Functional impact
It would be awesome to select an URL "folder like" and use files array to download several files from there.

### Minimal repro steps

    {
      "provider": "filesystem",
      "library": "https://raw.githubusercontent.com/twbs/bootstrap/v4.1.3/dist/js/",
      "files": [
        "bootstrap.js","bootstrap.min.js","bootstrap.min.js.map"
      ],
      "destination": "wwwroot/lib/bootstrap"
    }

### Expected result
"bootstrap.js","bootstrap.min.js","bootstrap.min.js.map" inside "wwwroot/lib/bootstrap"

### Actual result

    An unknown exception occurred

**Comment by nickalbrecht** [comment]
The folder structure of the files can be important for JS, CSS, or other assets as well. Stripping out some folder names like that can break functionality if the assets are not in the locations that are expected.

**Comment by aureole82** [comment]
As I mentioned: It would be nice to have a provider ("filesystem", "url" or anything else) that let me download more than one file.
@nickalbrecht: It don't need sub folders inside `"files":[]`

**Comment by jimmylewis** [comment]
There isn't a reliable way to enumerate the directory contents from a URL, so implementing this would require fairly significant changes to how the filesystem provider (and all providers) are allowed to work.  We wouldn't be able to give completions, or show the file list in the wizard, or validate that the manifest was valid, etc.  Glob patterns simply wouldn't work either.

This doesn't fit well, and there hasn't been significant requests for it.  GitHub support is now (in many cases) available through the JSDelivr provider, so hopefully that is enough to mitigate this need if the NPM catalog is not sufficient.
