### ISSUE TITLE
How to track dependencies on UNPKG

### ISSUE THREAD

**Issue by frankabbruzzese** [aspnet/LibraryManager#387]
Are there any plans to track npm package dependencies on UNPKG somehow? Adding all dependencies manually is tedious and error prone also in simple cases. I undestand that complex dependencies can be handled only with bundlers, but for simple cases where LibraryManager is used as an alternative to the deprecated Bower, some kind of interactive help might be very useful.

**Comment by jimmylewis** [comment]
No, that is not on our radar.  LibMan is intended to consume redist-ready libraries from multiple sources; it is not intended to handle package dependencies.  Our view is that the dependency and bundling problems are already solved by other toolsets, and we're providing an alternative for users whose use cases are too simple to warrant those toolsets.
