### ISSUE TITLE
inconsistent library name completion behavior, varies by provider

### ISSUE THREAD

**Issue by jimmylewis** [aspnet/LibraryManager#394]
### Functional impact
Inconsistent experience.  Behavior for CDNJS is much more usable than with other providers.  This also applies in the Add Client Side Library wizard, though less severely.

### Minimal repro steps

1. In the libman.json file, add a new library with the CDNJS provider
2. Type a library name, then tab to complete (Note: it completes the name@latest_version)
3. Add a library with jsdelivr or unpkg as the provider
4. Type a library name, then tab to complete

### Expected result
Same behavior as CDNJS - complete with name and version. Latest version seems good; arguably it could open completion for the version, but I think latest is more often the right call.

### Actual result
Completes the name, and moves the caret outside of the value so the user has to move it back in before typing @ and a version.

**Comment by alexgav** [comment]
Showing completion list may be better for technical reasons (getting latest version number is a separate async call and may not be ready when name is completed). We might pop up completion with "loading" initially and then replace that with the actual version list (as we do for package.json for npm). 

I think this should be P1 as it's very confusing to use unpkg and jsdeliver without it.

**Comment by alexgav** [comment]
Also see https://github.com/aspnet/LibraryManager/issues/383 - another example of why we should fix this soon.

**Comment by bsimser** [comment]
Another one to add. Some of the libraries have an "@" in their names so something like "@progress/kendo-ui" is a valid package, but then if you type "@" at the end of it, you don't get the intellisense for the version.

**Comment by jimmylewis** [comment]
@bsimser can you open a separate issue to track your problem?  Please include which provider(s) you're using in that scenario.

**Comment by jimmylewis** [comment]
This issue was fixed with #507
