### ISSUE TITLE
Request: publish NPM tool

### ISSUE THREAD

**Issue by StevenLiekens** [aspnet/LibraryManager#406]
Maybe I'm crazy but I'd like you to publish LibMan on the NPM registry so that it can be installed as a devDependency for Node.js projects.

The desired outcome is that I can use NPM to acquire LibMan CLI on a per-project basis instead of globally, and then use LibMan to install JS dependencies from NPM (via filesystem) or from a CDN if no NPM package is available.

```sh
# one-time setup
npm install --save-dev @aspnet/libman
npx libman init --default-provider filesystem --default-destination lib

# install some packages, eg. jQuery
npm install --save jquery
npx libman install ./node_modules/jquery --files dist/jquery.min.js
```

```jsonc
// final package.json
{
  "dependencies": {
    "jquery": "^3.3.1"
  },
  "devDependencies": {
    "@aspnet/libman": "^1.0.163"
  },
  "scripts": {
    "postinstall": "libman restore"
  }
}
```

```jsonc
// final libman.json
{
  "version": "1.0",
  "defaultProvider": "filesystem",
  "defaultDestination": "lib",
  "libraries": [
    {
      "library": "./node_modules/jquery",
      "files": [
        "dist/jquery.min.js"
      ]
    }
  ]
}
```

The expected result with this config is that `npm install` ensures that
- `libman` is available in `{workspace}/node_modules/.bin`
- `libman restore` is executed whenever you do `npm install`

A lot of this is already possible so the real goal is removing the need to manually do `dotnet tool install`.

**Comment by StevenLiekens** [comment]
PS this would bring libman installation in line with how Bower is installed
https://bower.io/#install-bower

This would be good for adoption in NPM projects that don't (want to) depend on dotnet cli.

**Comment by jodavis** [comment]
@StevenLiekens It's interesting that you would suggest this. We assumed that there are already well-established options for the Node.js ecosystem, so Node.js users would not be interested in LibMan's functionality.

Are you suggesting that the npm package would simply wrap the existing .NET-based tool (I.e. you would still need to install .NET Core to run it)? Or are you thinking of a whole new LibMan implementation written in JavaScript and running on Node.js?

**Comment by StevenLiekens** [comment]
The only real option for JS library management right now is NPM. And it only works well with packages that use Node's `require()` and `module.exports`, which is super weird for code that is intended to run in the browser (jQuery is the perfect example).

Basically I think LibMan is what npm-cli should have been, at least for front-end development. So it would be really cool if I could run LibMan with "npm run".

I think a wrapper would be good enough. The wrapper could print instructions on how to install .NET Core if it's not already available.

**Comment by jimmylewis** [comment]
I'm going to close this as out-of-scope.  I don't think we want to take that on, especially the support overhead of having to get .NET Core installed (and troubleshooting when it fails) or relying on users to have to read a message from their NPM restore to see that they have to take manual steps.
