### ISSUE TITLE
Ability to disable LibMan restore on build without removing package

### ISSUE THREAD

**Issue by AdamWillden** [aspnet/LibraryManager#408]
I'm raising this as a side effect of [the package restore operation being so slow](https://github.com/aspnet/LibraryManager/issues/389#issuecomment-437901025). 

Because libman (namely with unpkg provider) regularly takes >20s or experiences timeouts we regularly disable restore on build. However restore on build is required for CI to produce usable artifacts.

On multiple occasions we've subsequently/accidentally committed the removal of the package, effectively breaking our artifacts.

I'd like there to be consideration for another means of enabling/disabling libman restore on build that only affects the local machine. E.G. persist the option to the hidden `.vs` folder if that's at all possible.

**Comment by jodavis** [comment]
The LibraryManager targets check for a property called `LibraryRestore` before restoring files. If the value is 'False', restore should not happen on build. You can either set that conditionally in your project file, or set it as an environment variable in your dev environment.

**Comment by AdamWillden** [comment]
Thanks for the response. I think I can make that work :-)

**Comment by AdamWillden** [comment]
@jodavis thanks again, I can confirm this works for us in our csproj

```xml
  <PropertyGroup>
    <LibraryRestore>false</LibraryRestore>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <LibraryRestore>true</LibraryRestore>
  </PropertyGroup>
```

**Comment by jodavis** [comment]
Excellent, glad that helped. :)

**Comment by fatmazayedsayed** [comment]
i tried also to disable the libman file
right-click disable client side
