### ISSUE TITLE
Windows or Linux Slashes

### ISSUE THREAD

**Issue by clintnetwork** [aspnet/LibraryManager#412]
Hello,

I develop a project (stratis.guru) and I use libman, it's a great tool but the problem is that i code on windows so libman.json file is like this:
```
{
  "version": "1.0",
  "defaultProvider": "unpkg",
  "libraries": [
    {
      "library": "bootstrap@4.1.3",
      "destination": "wwwroot\\lib\\bootstrap"
    },
    {
      "library": "jquery-countdown@2.2.0",
      "destination": "wwwroot\\lib\\jquery-countdown"
    },
    {
      "library": "nprogress@0.2.0",
      "destination": "wwwroot\\lib\\nprogress"
    },
    {
      "library": "@aspnet/signalr@1.1.0",
      "destination": "wwwroot\\lib\\@aspnet/signalr"
    }
  ]
}
```

When i deploy the app on a linux server, and when I use libman restore, I get new folders like this: "wwwroot\lib\@aspnet/signalr" and not lib in wwwroot etc

It's a big problem, does there are a solution ?

**Comment by jimmylewis** [comment]
Using `/` as the path delimiter in your destination should work correctly on both operating systems.

**Comment by clintnetwork** [comment]
Hmm i can try

**Comment by jimmylewis** [comment]
#366 should track addressing this with some user experience to suggest using forward slashes
