### ISSUE TITLE
using LibraryManager download element-ui error

### ISSUE THREAD

**Issue by KaneLeung** [aspnet/LibraryManager#413]
download element@2.4.11 via cdnjs
show 【LIB010 无法从 "https://cdnjs.cloudflare.com/ajax/libs/element-ui/2.4.11/locale/bg.min.js.map" 下载资源】
mean can't download this resource

**Comment by jimmylewis** [comment]
I can't reproduce this issue.  It may have been a point-in-time problem, or just a flaky connection (which wouldn't show up nearly as often since the retry was added in 2.0.22).
