### ISSUE TITLE
Wildard support?

### ISSUE THREAD

**Issue by nickalbrecht** [aspnet/LibraryManager#42]
Is there a story for using wildcards for including multiple/all files? For example, something like this...

```json
{
  "version": "1.0",
  "defaultProvider": "cdnjs",
  "libraries": [
    {
      "library": "font-awesome@4.7.0",
      "files": [ "css/font-awesome.css", "fonts/*" ],
      "destination": "wwwroot/vendor/font-awesome"
    }
  ]
}
```

As an additional example, an icon library like `open-iconic` (one of the officially recommended ones for Bootstrap 4) has a ton of png images, and other assets. How would those be pulled in?

**Comment by nickalbrecht** [comment]
Update:
Found that omitting the files collection entirely defaults to all files. Though it'd be nice to be able to specify a folder's children explicitly using a wildcard.

As a continuation of my example above, the following example fails on the very first `webp` file (specifically `webp/account-login-2x.webp`) with this message in the Library Manager output window

> webp/account-login-2x.webp could not be written to disk. Make sure the file name is correct

The webp files are in the `desiredState.Files` collection, but the cache folder it's trying to copy from is missing the webp folder in it's entirety.
```json
{
  "version": "1.0",
  "defaultProvider": "cdnjs",
  "libraries": [
    {
      "library": "open-iconic@1.1.1",
      "destination": "wwwroot/vendor/open-iconic"
    },
  ]
}

```

**Comment by SaphuA** [comment]
I would love support for either wildcards or just specifying a directory as a file. Both supported cdn's support viewing directory contents so this should be possible.

**Comment by CodesMahoney** [comment]
how does this get attention, cuz i completely agree.

**Comment by jimmylewis** [comment]
Support for minimatch-based globs added in #534.  This will show up in the VS 16.5 preview releases (we'll release NuGet packages at the same time; packages supporting this feature will be versioned 2.1 or higher).  

We look for any of `*?[` to determine if a specified file is a pattern, as well as a leading `!` for exclusions.  `**` can be used to match any level of folder, as in the bootstrap example [above](https://github.com/aspnet/LibraryManager/issues/42#issuecomment-450851125).  Any file specified which does not match these new rules will behave exactly as it does today.
