### ISSUE TITLE
Unpkg Restore Failing Due to 301

### ISSUE THREAD

**Issue by salscode** [aspnet/LibraryManager#430]
### Functional impact
Unable to download libraries from unpkg until this is resolved.

### Minimal repro steps
Using VS 15.9.5, attempt to restore a package from unpkg.

### Expected result
I would expect the restore to work.

### Actual result
The restore fails.
```
The "@coreui/coreui@2.1.3" library could not be resolved by the "unpkg" provider
The "@coreui/coreui-plugin-chartjs-custom-tooltips@1.2.0" library could not be resolved by the "unpkg" provider
The "pace-progress@1.0.2" library could not be resolved by the "unpkg" provider
Restore operation completed with errors
========== Finished ==========
```

### Further technical details
Using fiddler, I confirmed that libman is requesting HTTP but is hitting a 301 to HTTPS.

**Comment by jimmylewis** [comment]
When I try to restore packages from unpkg, I see the 301s, but it still downloads all the files fine for me.  Do you have any special network configuration that might prevent the redirects from working?

**Comment by jimmylewis** [comment]
The unpkg provider was converted to use https in #436.
