### ISSUE TITLE
delete key is not captured by add client-side library., only backspace. 

### ISSUE THREAD

**Issue by user135711** [aspnet/LibraryManager#447]
### Functional impact
Unexpected

### Minimal repro steps

1. right click project,  add client side library
2. press delete while cursor is in Target Location

### Expected result
Text is deleted from the Target location field

### Actual result
The solution explorer project which is still selected is deleted with a confirmation dialogue.

**Comment by jimmylewis** [comment]
This seems to be fixed by #493 as well.
