### ISSUE TITLE
Lib006 error returned

### ISSUE THREAD

**Issue by hzexe** [aspnet/LibraryManager#458]
Step1: Install libman by :
``` Bash
dotnet tool install -g Microsoft.Web.LibraryManager.Cli
```
Step2:Add library by vs 2019 pre,the libman.json like this
``` JSON
{
  "version": "1.0",
  "defaultProvider": "cdnjs",
  "libraries": [
    {
      "ProviderId": "cdnjs",
      "DestinationPath": "wwwroot/lib/twitter-bootstrap/",
      "Files": [
        "js/bootstrap.min.js",
        "css/bootstrap.min.css"
      ],
      "IsUsingDefaultProvider": true,
      "IsUsingDefaultDestination": false,
      "Name": "twitter-bootstrap",
      "Version": "4.3.1"
    }
  ]
}
```
step3:Run cmd and cd to the directory that same as libman.json,then run
``` Bash
libman restore
```
The output is like [Lib006]: and some garbled following, and cmd windows will crash if try to copy the output string.

**Comment by jimmylewis** [comment]
Hi @hzexe, which build of VS2019 do you have?  This sounds like an issue that should have been fixed with #390.

**Comment by hzexe** [comment]
@jimmylewis 
Microsoft Visual Studio Enterprise 2019 Preview
VisualStudio.16.Preview/16.0.0-pre.1.1+28408.50

And reference package in msbuild program
```xml
<PackageReference Include="Microsoft.Web.LibraryManager.Build" Version="1.0.172" />
```
May be cause by vs or Microsoft.Web.LibraryManager.Build ?

**Comment by jimmylewis** [comment]
@hzexe it was a serialization issue when generating the library entry in VS.  It should be fixed in newer versions of the VS2019 preview (I just tried and got the content below), which I would recommend you update to.

To fix it this I think you need this content instead:
```
{
  "version": "1.0",
  "defaultProvider": "cdnjs",
  "libraries": [
    {
      "library": "twitter-bootstrap@4.3.1",
      "destination": "wwwroot/lib/twitter-bootstrap/",
      "files": [
        "js/bootstrap.min.js",
        "css/bootstrap.min.css"
      ]
    }
  ]
}
```
