### ISSUE TITLE
[loc][Query][LibraryManager]Localizability of 0; "(...) oreOnBuild|ButtonText"

### ISSUE THREAD

**Issue by PDostalek** [aspnet/LibraryManager#460]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Could you help please? Thanks!**

Source:
Enable Restore Client-Side Libraries on Build...

File Name:
LibraryManager.Vsix\Commands\CommandTable\LocalizationFiles\VSCommandTable.xlf

Resource ID:
0; "(...) oreOnBuild|ButtonText"

Query:
Could you clarify what "on Build" exactly refers to? Does it mean "during build time"?

**Comment by jimmylewis** [comment]
@PDostalek yes, this means that we will restore the client-side libraries as part of the project build.  During build time is an appropriate way to say it.

**Comment by PDostalek** [comment]
Thanks!
