### ISSUE TITLE
UX issues when using non-default provider

### ISSUE THREAD

**Issue by mqudsi** [aspnet/LibraryManager#461]
In Visual Studio 16, when adding a package to `libman.json`, the default behavior when selecting a package from the display intellisense list of the provider's packages to tack on `@foo` where `foo` is the latest available version of the package. This works 100% when using the default provider (cdnjs) and everything is groovy.

When a different provider is instead specified, pressing `enter` to choose the highlighted intellisense option from the autocompletion list merely results in the name of the package being populated within the quotes, there is no `@foo` appended.

### Functional impact
* Packages not restored if the user does not catch the error
* Future autocomplete (such as files to include in the restore) is broken/unavailable

### Minimal repro steps

```json
{
  "version": "1.0",
  "defaultProvider": "cdnjs",
  "defaultDestination": "wwwroot/lib/",
  "libraries": [
    {
      "provider": "unpkg",
      "library": "almon
```

at this point, `almond` should be visible in the intellisense completion of packages. Selecting it results in `"library": "almond",` rather than `"library": "almond@0.3.3",`

**Comment by mqudsi** [comment]
I apologize, this is a duplicate of #394

**Comment by jimmylewis** [comment]
Closing as a duplicate.
