### ISSUE TITLE
[loc][Query][LibraryManager] Localizability of string:  "Checked {0}"/ UnChecked {0}

### ISSUE THREAD

**Issue by PDostalek** [aspnet/LibraryManager#462]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Could you help please? Thanks!**

Source:
Checked {0}
UnChecked {0}

File Name:
LibraryManager.Vsix\MultilingualResources\Microsoft.Web.LibraryManager.Vsix.xlf

Resource ID:
0; "MICROSOFT.WEB.LIBRARYMANAGER.VSIX/RESOURCES/TEXT.RESX.Checked"
0; "MICROSOFT.WEB.LIBRARYMANAGER.VSIX/RESOURCES/TEXT.RESX.UnChecked"

Query:
Please explain the placeholders. Thanks.

**Comment by jimmylewis** [comment]
This string was added for exposing the state of tree items rendered as checkboxes file picker to a screen reader.  The placeholders would contain a description of each item (I believe it's a filename).  There is no punctuation between them to match the default behavior of checkboxes.

/cc @bhsubra

**Comment by PDostalek** [comment]
Thanks for an explanation
