### ISSUE TITLE
[loc][Query][LibraryManager] Localizability of string:  "Stable: {0}"

### ISSUE THREAD

**Issue by PDostalek** [aspnet/LibraryManager#463]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Could you help please? Thanks!**

Source:
Stable: {0}

File Name:
LibraryManager.Vsix\MultilingualResources\Microsoft.Web.LibraryManager.Vsix.xlf

Resource ID:
0; "MICROSOFT.WEB.LIBRARYMANAGER.VSIX/RESOURCES/TEXT.RESX.SuggestedAction_Update_Stable"

Query:
Please clarify the meaning of the string and the placeholder. What exactly is stable?

**Comment by jimmylewis** [comment]
The feature here proposes which version an existing library will be updated to.  We use this string to distinguish a stable version from a pre-release version.  The placeholder that follows is a version number (e.g. `Stable: 1.2.3`)

**Comment by PDostalek** [comment]
Many thanks!
