### ISSUE TITLE
file permissions incorrect after adding signalR to new webapp on ubuntu?

### ISSUE THREAD

**Issue by rakkarage** [aspnet/LibraryManager#475]
### Functional impact
file permissions incorrect after adding signalR to new webapp on ubuntu?

### Minimal repro steps
after adding signalR using 

`libman install @aspnet/signalr -p unpkg -d wwwroot/lib/signalr --files dist/browser/signalr.js --files dist/browser/signalr.min.js`

from

https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.2&tabs=visual-studio

the file permissions are like this

![Untitled](https://user-images.githubusercontent.com/962340/57001292-e3e88680-6b85-11e9-980c-e9e24c35e310.png)

so it works locally but when run on server get error because public cannot see it

![222](https://user-images.githubusercontent.com/962340/57001323-1befc980-6b86-11e9-9e71-d2279151a8ff.png)

`sudo chmod 664 filename`

fixes it 

### Expected result

even a new sln or project file is generated with more permissions then these files? should or could it start with default 664 like most other generated files? since these permissions create an 'error' without a 'good' error message

or maybe i am just missing a setting or something
or maybe it is something with those permission and dotnet publish
thanks

**Comment by jimmylewis** [comment]
This should be fixed in the CLI or Build NuGet packages version 2.0.76 or higher.
