### ISSUE TITLE
Existing library files prevent restore from updating files to different version

### ISSUE THREAD

**Issue by ducman** [aspnet/LibraryManager#478]
### Functional impact
Restore does not pull down library files if those files already exist.

### Minimal repro steps
1. Enable "Restore on Build".
2. Add a library from unpkg (any with the latest version).
3. Notice library files are restored.
4. Outside of VS (notepad), update libman.json and set library version to an older version.
5. In VS, do a build.
6. Notice that old version files aren't pulled down.

### Expected result
Correct version of the library files are restored.

### Actual result
Library files remain untouched. They never updated to the correct version.

### Further technical details
Step 4 can be some outside entity updating the libman.json file. For example, developer A add a library and commit/push. Developer B pulls and update library to an newer version; he/she then commit/push. Developer A pulls and build; because library files already exists for him/her, newer version of the files are never pulled down. A clean and then a restore fixes this issue since clean remove all existing files.

But in azure devops, it is setup to "Restore on Build" which does not do a clean so the build server have all the existing files and they are never updated if a library version has changed. Our workaround right now on azure devops is that we added a task to delete the library files so that during the build task, the "Restore on Build" would pull down these library files with the correct version.

**Comment by bzhu94** [comment]
What version of VS and Libman are you on? This doesn't repro on the latest VS 2019, so could you see if that works for you?
