### ISSUE TITLE
 [loc][Query][LibraryManager] Localizability of string:  "CdnjsLibraryIdHintText"

### ISSUE THREAD

**Issue by PDostalek** [aspnet/LibraryManager#479]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Could you help please? Thanks!**

Source:
Example: <it id="1" pos="open">&lt;library&gt;</it>@<it id="2" pos="open">&lt;version&gt;</it>

File Name:
LibraryManager\MultilingualResources\Microsoft.Web.LibraryManager.xlf

Query:
Are the words "library" and "version" localizable?

**Comment by jimmylewis** [comment]
Yes, these terms are localizable.

**Comment by PDostalek** [comment]
Thanks!
