### ISSUE TITLE
Update does not update any existing files

### ISSUE THREAD

**Issue by ygoe** [aspnet/LibraryManager#490]
When any client-side library files were already downloaded, nothing is updated when the libman.json file is changed. Even on explicit "restore" from the Visual Studio solution context menu, nothing happens. The old files just stay where they are, untouched.

The known workaround is to first delete all existing files that are known to have changed, then start the restore command again. The current files will then be downloaded and placed locally.

Using Visual Studio 2017 v15.9.13 with Microsoft Library Manager v1.0.151.20037 on Windows 10.

The error specifically occured with the package @ygoe/msgpack updating from v1 to v1.0.2 and the following libman.json file:

```
{
  "version": "1.0",
  "defaultProvider": "unpkg",
  "libraries": [
    {
      "library": "@ygoe/msgpack@1.0.2",
      "destination": "wwwroot/lib/msgpack/",
      "files": [
        "msgpack.js",
        "msgpack.min.js",
        "msgpack.min.js.map"
      ]
    },
    {
      "library": "jquery@3.4.1",
      "destination": "wwwroot/lib/jquery/",
      "files": [
        "dist/jquery.js",
        "dist/jquery.min.js",
        "dist/jquery.min.map"
      ]
    },
    {
      "library": "luxon@1.12.0",
      "destination": "wwwroot/lib/luxon/",
      "files": [
        "build/global/luxon.js.map",
        "build/global/luxon.js",
        "build/global/luxon.min.js",
        "build/global/luxon.min.js.map"
      ]
    }
  ]
}
```

**Comment by bzhu94** [comment]
This doesn't repro for me on the latest VS 2019 build, can you try that out and see if this works? If you can't be on VS 2019, for VS 2017 you'll probably have to use command line `libman update` to update your library versions.
