### ISSUE TITLE
[loc][Query][LibraryManager] Localizability of string: Checked {0} {1}

### ISSUE THREAD

**Issue by PDostalek** [aspnet/LibraryManager#492]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Could you help please? Thanks!**

Source:
Checked {0} {1}

File Name:
LibraryManager.Vsix\MultilingualResources\Microsoft.Web.LibraryManager.Vsix.xlf

Resource ID:
0; "MICROSOFT.WEB.LIBRARYMANAGER.VSIX/RESOURCES/TEXT.RESX.Checked"
0; "MICROSOFT.WEB.LIBRARYMANAGER.VSIX/RESOURCES/TEXT.RESX.UnChecked"

Query:
Could you kindly provide resulting sample strings to check if our translation of the below strings work, please? Screenshot or examples of use could be good.

0; "MICROSOFT.WEB.LIBRARYMANAGER.VSIX/RESOURCES/TEXT.RESX.Checked"
0; "MICROSOFT.WEB.LIBRARYMANAGER.VSIX/RESOURCES/TEXT.RESX.Indeterminate"
0; "MICROSOFT.WEB.LIBRARYMANAGER.VSIX/RESOURCES/TEXT.RESX.UnChecked"
0; "GroupByColumnDescriptorFormat"

**Comment by jimmylewis** [comment]
There's a comment in the .resx file explaining this: https://github.com/aspnet/LibraryManager/blob/aa3f5782edf8c828d6803db8539b054d7feb1901/src/LibraryManager.Vsix/Resources/Text.resx#L240

Is there a better way we can put comments in the resource files so that the localization team can find them?

**Comment by PDostalek** [comment]
In most cases comments are enough to know the context. Otherwise we would ask for better clarification.
Could you please provide real use of this strings? screenshots..etc ?

**Comment by jimmylewis** [comment]
These 3 strings (Checked/Unchecked/Indeterminate) are for screen readers to indicate the state of the checkboxes in the file picker.  We've added more data to the string to indicate whether the item represented by the checkbox is a file or a folder.

**Comment by PDostalek** [comment]
Thanks, that should be enough to know I think.
