### ISSUE TITLE
Microsoft.Web.LibraryManager.Build.RestoreTask exception

### ISSUE THREAD

**Issue by ImGonaRot** [aspnet/LibraryManager#514]
Microsoft.Web.LibraryManager.Build 2.0.76
VS 2017 15.9.11
ASP.NET Web Form project using 4.6.1

On some machine in our office using VS 2017, we can't build our ASP.NET project that has the "auto restore" enabled for LibMan.
Some machines with VS 2017 using the same project build fine.

What seems to be odd is that our ASP.NET project references "System.Net.Http Version 4.0.0.0" yet the LibraryManager is referencing "System.Net.Http Version 4.2.0.0".
I think this is either a bad reference pointing to a file not installed on users machines or not using the GAC version of System.Net.Http.

We get the following:
1>...\packages\Microsoft.Web.LibraryManager.Build.2.0.76\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018: The "Microsoft.Web.LibraryManager.Build.RestoreTask" task failed unexpectedly.
1>...\packages\Microsoft.Web.LibraryManager.Build.2.0.76\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018: System.TypeInitializationException: The type initializer for 'Microsoft.Web.LibraryManager.WebRequestHandler' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
1>...\packages\Microsoft.Web.LibraryManager.Build.2.0.76\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Web.LibraryManager.WebRequestHandler..ctor(ProxySettings proxySettings)
1>...\packages\Microsoft.Web.LibraryManager.Build.2.0.76\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Web.LibraryManager.WebRequestHandler..cctor()
1>...\packages\Microsoft.Web.LibraryManager.Build.2.0.76\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    --- End of inner exception stack trace ---
1>...\packages\Microsoft.Web.LibraryManager.Build.2.0.76\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Web.LibraryManager.WebRequestHandler.get_Instance()
1>...\packages\Microsoft.Web.LibraryManager.Build.2.0.76\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Web.LibraryManager.Providers.Unpkg.UnpkgProvider..ctor(IHostInteraction hostInteraction)
1>...\packages\Microsoft.Web.LibraryManager.Build.2.0.76\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Web.LibraryManager.Providers.Unpkg.UnpkgProviderFactory.CreateProvider(IHostInteraction hostInteraction)
1>...\packages\Microsoft.Web.LibraryManager.Build.2.0.76\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Web.LibraryManager.Build.Dependencies.Initialize()
1>...\packages\Microsoft.Web.LibraryManager.Build.2.0.76\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Web.LibraryManager.Build.Dependencies..ctor(IHostInteraction hostInteraction, IEnumerable`1 assemblyPaths)
1>...\packages\Microsoft.Web.LibraryManager.Build.2.0.76\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Web.LibraryManager.Build.RestoreTask.Execute()
1>...\packages\Microsoft.Web.LibraryManager.Build.2.0.76\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>...\packages\Microsoft.Web.LibraryManager.Build.2.0.76\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

**Comment by jimmylewis** [comment]
Can you try out the 2.0.96 version of the LibraryManager.Build package and see if it addresses the issue?  It has a change that might address this (or it might not - we'll see).

**Comment by senj** [comment]
I have the same issue:

```
The type initializer for 'Microsoft.Web.LibraryManager.WebRequestHandler' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

On hosted VSTS Agent with Visual Studio 2019 it works. Update to 2.0.96 didn't fix it.
Should it be supported on Visual Studio 2017?

**Comment by kant2002** [comment]
Same with VS2019 and .NET Core 3.1

**Comment by kant2002** [comment]
Actually I manage to fix that by specifying --framewok
Before:
```
dotnet publish --runtime win7-x64 --configuration Release
```
After:
```
dotnet publish --runtime win7-x64 --configuration Release --framework netcoreapp3.1
```

**Comment by xiwan** [comment]
> Actually I manage to fix that by specifying --framewok
> Before:
> 
> ```
> dotnet build --runtime win7-x64 --configuration Release
> ```
> 
> After:
> 
> ```
> dotnet build --runtime win7-x64 --configuration Release --framework netcoreapp3.1
> ```

Hey kant2002,

I did as you guide. But the error still there. 

dotnet build --configuration Release --runtime linux-x64 --framework netcoreapp3.1

PS, the env is within docker.

**Comment by amoraitis** [comment]
Updating to the latest `Microsoft.Web.Library.Manager.Build -v 2.1.76` solves that error for me.

**Comment by jimmylewis** [comment]
Seems this was solved in the 2.1.76 package, so resolving the issue.

**Comment by NewToScripting** [comment]
In case anyone is facing this issue, what worked for me is deleting the .packages folder at the solution level for the nuget packages referenced. then I restored the nuget packages and everything build again.

**Comment by kibblewhite** [comment]
2025 and still fighting with this one
