### ISSUE TITLE
Error copying files after a certain point, using a library with a large number of files

### ISSUE THREAD

**Issue by nickalbrecht** [aspnet/LibraryManager#52]
This is a stand alone issue for a [remark](https://github.com/aspnet/LibraryManager/issues/42#issuecomment-377012195) I made under #42.

Specifically when using a library with a large number of files (like [open-iconic](https://useiconic.com/open), which is one of the recommended libraries for use with Bootstrap 4), it seems to encounter an error eventually where the [stream](https://github.com/aspnet/LibraryManager/blob/a94f9c801915f52958c1e9739aa5428f3cc58a99/src/LibraryManager.Vsix/Contracts/HostInteraction.cs#L39) is null.

Below is the `libman.json` file to reproduce the problem.
```
{
  "version": "1.0",
  "defaultProvider": "cdnjs",
  "libraries": [
    {
      "library": "open-iconic@1.1.1",
      "destination": "wwwroot/vendor/open-iconic"
    },
  ]
}
```

**Comment by OzBob** [comment]
Replicated on VS 15.9.0 Preview 3.0

Adding open-ionic using LibMan:

After 9 minutes of downloading the LibMan Output is as follows:

Restore operation started...
Restoring libraries for project Web2
Restoring library open-iconic@1.1.1... (Web2)
Failed to download resource from "https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/webp/account-login-2x.webp"
Restore operation completed
1 libraries failed to restore
Time Elapsed: 00:09:33.7451663
========== Finished ==========

**Comment by OzBob** [comment]
As an aside: raised the fact that the file is missing on CDNJS https://github.com/iconic/open-iconic/issues/42

**Comment by nickalbrecht** [comment]
Cleaning up older issues. I just tested the most recent version of Microsoft.Web.LibraryManager.Build (2.0.96) with a new project, and open-iconic@1.1.1 restored successfully. so I'm considering this closed.
