### ISSUE TITLE
libman restore fails in CI using .net core 3.0 sdk image

### ISSUE THREAD

**Issue by los93sol** [aspnet/LibraryManager#520]
I have been using the mcr.microsoft.com/dotnet/core/sdk:2.2-stretch image in my CI/CD builds for awhile now without issue.  Now that .Net Core 3.0 is released I am upgrading my project to it and having issues with my CI/CD build.  When using mcr.microsoft.com/dotnet/core/sdk:3.0.100-buster I install libman as follows...

$ dotnet tool install -g Microsoft.Web.LibraryManager.Cli
You can invoke the tool using the following command: libman
Tool 'microsoft.web.librarymanager.cli' (version '2.0.76') was successfully installed.

Cool so it installed libman without issue, but when it tries to restore things go sideways.

$ libman restore
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.0.0 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The .NET Core frameworks can be found at:
  - https://aka.ms/dotnet-download

And according to the documents the pre-requisite is .Net Core 2.1 or later, but 3.0 is later and it doesn't seem to be working.  I've triple checked my entire repository and I have no reference to Microsoft.NETCore.App 2.1.0

**Comment by los93sol** [comment]
Looks like it’s probably because of this https://github.com/aspnet/LibraryManager/blob/bb515bf382e7e7a4d67eb62a425468230cf36906/src/libman/libman.csproj#L5

I can think of a few ways to workaround this issue, but none of them are really great solutions.

I could retarget, build it myself, and rebuild the 3.0.100-buster image with it prebuilt which I guess is probably not terrible since I could skip the tool install in my CI builds.

I could just restore locally and commit them to the repo which means I could skip the restore in my CI builds.  As wrong as that feels it’s probably the path of least resistance and I guess eliminates issues with other developers on my team who may not clean their client side packages and restore when an updated package goes in.

Any thoughts on this?  Other workarounds I haven’t though about?

**Comment by jimmylewis** [comment]
This should be fixed in the 2.0.96 build.  Can you upgrade and give it a try?
