### ISSUE TITLE
[Menu items] "Add->Client-Side Libraries" not showing on Visual Studio for Mac 2019

### ISSUE THREAD

**Issue by tomaszkyc** [aspnet/LibraryManager#536]
### Functional impact
*Does the bug result in any actual functional issue, if so, what?*  
e.g. Can't open / use libman UI version inside Visual Studio for Mac.

### Minimal repro steps
*What is the smallest, simplest set of steps to reproduce the issue. If needed, provide a project that demonstrates the issue.*  

1. Install Visual Studio for Mac version 8.3.8 (build 8)
2. Create ASP.NET Core 3.0 web project
3. Install using NuGet package named "Microsoft.Web.LibraryManager.Build"
4. Restart Visual Studio for Mac to see if menu item showed up.

### Expected result
*What would you expect to happen if there wasn't a bug*  
The menu item **"Add->Client-Side Libraries"** should appear.

### Actual result
*What is actually happening*  
The menu item **"Add->Client-Side Libraries"** does not appear as below:
![libman-error-1](https://user-images.githubusercontent.com/32226044/68799725-f5443c80-0658-11ea-83c3-ad4e2b86023f.png)

### Further technical details
Not available

**Comment by jimmylewis** [comment]
We currently don't have any support for Libman in VS Mac, but it is something we need to keep under consideration until we can fund it.

**Comment by jimmylewis** [comment]
Turns out, there's a fork of the project as a VS for Mac add-in.  Resolving this based on https://lastexitcode.com/blog/2019/07/13/LibManSupportInVisualStudioMac8-1/, and we'll look at integrating it back to the main project at some point in the future.

**Comment by rajkiranmehra** [comment]
Have you found out any solution for this

**Comment by NishantGautam023** [comment]
<img width="636" alt="image" src="https://user-images.githubusercontent.com/47427428/230173229-bd36cc75-75a9-4427-a48c-4816761cac89.png">

Currently using the Visual Studio 2022 community edition,  I don't see an option for **adding Client-Side Library in visual studio 2022 for Mac users**
<img width="372" alt="image" src="https://user-images.githubusercontent.com/47427428/230173451-11e6e30a-bb1b-4e71-8190-ad23afac2f28.png">
