### ISSUE TITLE
On Add Library Manage Window Switch input method, VS will restart

### ISSUE THREAD

**Issue by mzy666888** [aspnet/LibraryManager#540]
### Functional impact
When I Add library on Library manage window，if input method is chinese ,I Inputing one Half a word. I switch input method on press key `shift`， the vs will restart。

### Minimal repro steps

1. open library manage window
2. sure input method on chinese input method ,use  **Microsoft Pinyin input method**
![image](https://user-images.githubusercontent.com/2587129/71537315-4f713680-2955-11ea-9723-aa8856a0ea6b.png)

3. input Letter  like  `ad`, on this time I find input method is chinese ,and i want switch input method to English, so I press key `shift`
![image](https://user-images.githubusercontent.com/2587129/71537319-64e66080-2955-11ea-9dbb-722027d9d72c.png)

4. at step 3 ,the vs will restart

**Comment by jimmylewis** [comment]
I'm not able to reproduce this on my machine (ENU Windows, CHS Pinyin IME).  It sounds like the issue addressed by #433 but that was an old issue...

Can you confirm which build of VS you're using?  And the version of Microsoft Library Manager listed in the Help -> About dialog?

**Comment by mzy666888** [comment]
Today I try again,but its not restart.
VS verstion: 16.4.2
