### ISSUE TITLE
Adding SCSS files breaks the publish

### ISSUE THREAD

**Issue by tortocan** [aspnet/LibraryManager#564]
### Functional impact
Publish or build can`t be done by other developers without package restore as SCSS files are added to the project as <Content Include=>.
This is a Web Application running on Net Framework 4.7.1.
Issue only happens on VS2017 15.9.14

### Minimal repro steps

1. Add boostrap SCSS files:
``` 
 {
      "library": "bootstrap@4.4.1",
      "files": [
            "scss/_alert.scss"
      ],
      "destination": "css/lib/bootstrap/"
 }
```
2. Add .gitignore file (Optional):
`css/lib/**`
3.Delete manually the scss files:
![image](https://user-images.githubusercontent.com/11134055/78690822-3c78e580-78f8-11ea-91cc-3b214c3203c3.png)
4.Publish porject result:
![image](https://user-images.githubusercontent.com/11134055/78690919-54e90000-78f8-11ea-8242-4ccad3fb62e8.png)

### Expected result
```
    <None Include="css\lib\bootstrap\scss\_alert.scss" />
    <None Include="css\lib\bootstrap\scss\_badge.scss" />
    <None Include="css\lib\bootstrap\scss\_breadcrumb.scss" />
    <None Include="css\lib\bootstrap\scss\_button-group.scss" />
...
```

### Actual result
```
    <Content Include="css\lib\bootstrap\scss\_alert.scss" />
    <Content Include="css\lib\bootstrap\scss\_badge.scss" />
    <Content Include="css\lib\bootstrap\scss\_breadcrumb.scss" />
    <Content Include="css\lib\bootstrap\scss\_button-group.scss" />
..
```

### Further technical details
I don`t know if it makes sense to have this files included in the project as they are used only for development,
So the tag <None Include=> might be a solution to this issue.
Another solution will be to have .libmanignore and not add the files to the project content at all.

**Comment by tortocan** [comment]
temp fix
```
  <ItemGroup>
    <Content Update="**\*.map;**\*.less;**\*.scss" CopyToPublishDirectory="Never" />
  </ItemGroup>
```

**Comment by jimmylewis** [comment]
This is by-design.  LibMan always adds the items to the project - in most cases, they are CSS or JS files that are meant to be deployed.  Even in the case of other asset types, LibMan will always add to the project as it must assume that something in the project's build will consume those files (whether just copying to output for publishing, or another build task/pipeline job).

Maybe adding the [Microsoft.Web.LibraryManager.Build](https://www.nuget.org/packages/Microsoft.Web.LibraryManager.Build/) NuGet package would help, as it restores LibMan content during project build.

**Comment by tortocan** [comment]
It is true that Microsoft.Web.LibraryManager.Build will fix the issue still I do not understand why I will ever need TS, LESS or SCSS files in my publish folder.

**Comment by jimmylewis** [comment]
It's the project system that sets those as Content.  The same would happen if you add a loose file of those types to the project.  And the default behavior for publish pulls in any Content items.  Unfortunately, that's out of scope for LibMan to change.  You could try sending a VS feedback ticket for why those are treated as Content instead of None by default.
