### ISSUE TITLE
Access the library name property when settings the defaultDestination

### ISSUE THREAD

**Issue by Valks** [aspnet/LibraryManager#57]
It would be nice to be able to pass in the library name as a variable when setting the defaultDestination. That way the libraries could be stored in their own folders e.g.

"defaultDestination": "wwwroot/libs/{library.name}/"

Not sure on the best syntax but the above example I'd expect it to replace {library.name} with e.g. bootstrap

**Comment by RobJohnston** [comment]
This was brought up for discussion a couple weeks after you posted in #72 .

**Comment by jimmylewis** [comment]
Closing in favor of #438
