### ISSUE TITLE
Cannot install libman-cli

### ISSUE THREAD

**Issue by abmptit** [aspnet/LibraryManager#570]
### Functional impact
*Does the bug result in any actual functional issue, if so, what?*  
e.g. If poll request starts working again, it recovers. Otherwise, it sends many requests per sec to the servr.

### Minimal repro steps
*What is the smallest, simplest set of steps to reproduce the issue. If needed, provide a project that demonstrates the issue.*  

1. Open powershell termina
2. Run dotnet tool install --global Microsoft.Web.LibraryManager.Cli --version 2.0.96

### Expected result
Install the libman-cli

### Actual result
*Error message*  
Cannot restore the tool package...
Here in french the message:
Impossible de restaurer le package de l'outil.
Échec de l'installation de l'outil 'microsoft.web.librarymanager.cli'. Causes possibles de cet échec :

* Vous essayez d'installer une préversion, et vous n'avez pas utilisé l'option --version pour spécifier la version.
* Un package portant ce nom a été trouvé, mais il ne s'agit pas d'un outil .NET Core.
* Le flux NuGet nécessaire n'est pas accessible, peut-être en raison d'un problème de connexion à Internet.
* Vous avez mal tapé le nom de l'outil.

Pour plus d'informations, notamment sur le nommage de package, accédez à https://aka.ms/failure-installing-tool

**Comment by jimmylewis** [comment]
I'm able to install the tool normally.  I was also able to reproduce this issue when using NuGet.config file that removed Nuget.org as a source.  Can you double check if you've disabled or removed the Nuget.org source, either through a nuget.config file or through the Visual Studio Tools->Options->NuGet Package Manager->Package Sources settings?

**Comment by jimmylewis** [comment]
Without more information, there's nothing further I can investigate here.  Closing the issue for now.
