### ISSUE TITLE
Update CLI to 2.1

### ISSUE THREAD

**Issue by drauch** [aspnet/LibraryManager#573]
When will an update to LibMan 2.1 reach the master branch / the NuGet package at https://www.nuget.org/packages/Microsoft.Web.LibraryManager.Cli/ ?

We're waiting for a feature coming with LibMan 2.1 :-)

**Comment by jimmylewis** [comment]
Sorry about that, meant to get those out before.  Just published some new ones!

**Comment by drauch** [comment]
That was quick - thank you!
