### ISSUE TITLE
Feature request: Add possibility to exclude files

### ISSUE THREAD

**Issue by varogonz95** [aspnet/LibraryManager#578]
I would be great to exclude files using the command line interface or libman.json file.
This because in the case of ionicons, 403 error occurs because of cheatsheet.html file included in the library.

So, instead of adding ALL files, wouldn't be nice to just exclude this particular file?
For example:

CLI
`libman install ionicons@5.0.1 --exclude file1.html,file2.html`
and so on...

Or...

```
{
    //...
    "libraries": [
        "library": "ionicons",
        "exclude": [
            "file1.html",
            "file2.html"
        ],
        //or use glob pattern
        "files:" [
            "/**/*",
            "!file1.html",
            "!file1.html"
        ]
    ]
}
```

**Comment by jimmylewis** [comment]
The last example (exclude globs) should already be supported in the libman.json file with version 2.1 (or Visual Studio 16.5+).  This worked for me:

```
{
  "version": "1.0",
  "defaultProvider": "cdnjs",
  "libraries": [
    {
      "library": "ionicons@5.0.1",
      "destination": "wwwroot/lib/ionicons/",
      "files": [
        "**/*",
        "!esm/index.mjs",
        "!esm/ionicons.mjs",
        "!esm/loader.mjs",
        "!esm-es5/index.mjs",
        "!esm-es5/ionicons.mjs",
        "!esm-es5/loader.mjs",
        "!loader/index.es2017.mjs",
        "!loader/index.mjs",
        "!loader/ionicons.mjs",
        "!loader/loader.mjs",
        "!cheatsheet.html",
        "!index.mjs"
      ]
    }
  ]
}
```

Similarly, on the command line, using `--files **/* --files !somefile.html` generates the expected entries in the manifest as well (with the unfortunate pre-requisite that you need to know all the exclude files up front).
