### ISSUE TITLE
Changelog Is Not Being Maintained

### ISSUE THREAD

**Issue by TheHokieCoder** [aspnet/LibraryManager#581]
### Functional impact
*Does the bug result in any actual functional issue, if so, what?*  

No, nothing functional is impacted by this issue. It is simply a documentation issue.

### Minimal repro steps
*What is the smallest, simplest set of steps to reproduce the issue. If needed, provide a project that demonstrates the issue.*  

1. View the [CHANGELOG.md](/aspnet/LibraryManager/blob/master/CHANGELOG.md) file.
2. Notice that nothing has been updated in 3 years, so it is apparently not possible to view changes from release to release.

### Expected result
*What would you expect to happen if there wasn't a bug*  

The changelog and roadmaps should be updated with every release.

### Actual result

The changelog is being ignored.

### Further technical details

None.

**Comment by jimmylewis** [comment]
Updated now, and I'll try to keep this fresh as new releases come out.  Thanks for calling it out!
