### ISSUE TITLE
Document jsDelivr provider

### ISSUE THREAD

**Issue by MartinKolarik** [aspnet/LibraryManager#586]
Following up on https://github.com/aspnet/LibraryManager/pull/338#issuecomment-627138654, I think there are currently no docs on what exactly the provider supports and how it should be used, other than the initial post in the PR implementing it (#338). A summary similar to what's in the PR should probably be added to the [wiki](https://github.com/aspnet/LibraryManager/wiki).

This is important especially because by default even the GUI only lists npm packages. To use GitHub users need to be aware that it's possible and how to format the package name.

**Comment by jimmylewis** [comment]
Thanks for calling out the lack of documentation.  I've now listed all the providers [here](https://github.com/aspnet/LibraryManager/wiki/Providers), please let me know if I've left anything out with regards to JSDelivr.

**Comment by MartinKolarik** [comment]
Looks good, two small notes: latest works also with GitHub releases, and a branch name can now be used as well.

**Comment by jimmylewis** [comment]
I've now included both those cases, thanks for pointing them out.
