### ISSUE TITLE
Is there any variables that I can use to define defaultDestination ?

### ISSUE THREAD

**Issue by John0King** [aspnet/LibraryManager#589]
now libman.json  has the `defaultDestination` field, 
but it just one directory, people want to install the library to each folder by default 
such like 

```jsonc
{
    "defaultDestination":"wwwroot/lib/{library-name}"
}
```

and we still need the `path/subdir/*` to support only download sub directory install ，instead of list all files in the sub directory

**Comment by John0King** [comment]
any news about this ?

**Comment by RobJohnston** [comment]
Related to #407, needs a way to specify the destination relative to `defaultDestination`.

**Comment by RobJohnston** [comment]
Duplicate of https://github.com/aspnet/LibraryManager/issues/438, "Destination path pattern".
