### ISSUE TITLE
Support for Microsoft CDN alcdn.msauth.net 

### ISSUE THREAD

**Issue by iBrotNano** [aspnet/LibraryManager#591]
### Functional impact
It seems Microsoft has an own CDN service where some Microsoft libs are hosted.

https://github.com/AzureAD/microsoft-authentication-library-for-js is one.

Libman does not support the CDN.

**Comment by jimmylewis** [comment]
The MSAL libraries are also available via NPM, and hence via the other providers.  Because of this, I don't think we'll be able to prioritize a new provider for this niche CDN.
