### ISSUE TITLE
error LIB010 unable to download resource from the given 

### ISSUE THREAD

**Issue by aakashjoshi1386** [aspnet/LibraryManager#596]
Error	LIB010	Failed to download resource from "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/scss/_alert.scss" 
Hitting this below url will give 404 page 
https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/scss/_alert.scss 

Please could someone provide precise solution to this issue
I had googled it but not able to solve this

**Comment by jimmylewis** [comment]
This looks like either a catalog issue or a CDN issue on the cdnjs.com side.  All the .scss files show up in the catalog (also visible at https://cdnjs.com/libraries/twitter-bootstrap) but they all return 404s.  Can you try reporting this at https://github.com/cdnjs/cdnjs/issues and see if they can fix it?

**Comment by aakashjoshi1386** [comment]
Appreciate for the help, 
proud to be a member of GitHub.com
