### ISSUE TITLE
Failure To Install

### ISSUE THREAD

**Issue by JosephHubbard** [aspnet/LibraryManager#617]
### Describe the bug
error NU3028: Package 'Microsoft.Web.LibraryManager.Cli 2.1.113' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
error NU3037: Package 'Microsoft.Web.LibraryManager.Cli 2.1.113' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
error NU3028: Package 'Microsoft.Web.LibraryManager.Cli 2.1.113' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
The tool package could not be restored.
Tool 'microsoft.web.librarymanager.cli' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

### To Reproduce
Try any method of install this package using the DotNet command on a Linux machine. Very often with this bug stretching over the span of two years a contributor finds that the command works successfully on his machine and closes the issue. But this command patently DOES NOT work on my Kali system. The addage 'it's not the bug that appears everytime that is the worst, but the bug that appears 1/10 times' feels apt.

### Additional context
Doesn't matter if it's from Visual Studio's or the OS' terminal.

**Comment by jimmylewis** [comment]
I was able to reproduce this on Kali, but not on Ubuntu.  It seems to be the same issue as reported at https://github.com/NuGet/Announcements/issues/49.  Have you tried the steps indicated in that issue to mitigate?

After I updated this package:
>ca-certificates/kali-rolling 20210119 all [upgradable from: 20200601]

I was able to install the Microsoft.Web.LibraryManager.Cli package successfully.
