### ISSUE TITLE
Unable to Install With .NET 5.0 Windows

### ISSUE THREAD

**Issue by bdubose** [aspnet/LibraryManager#641]
### Description
I'm trying to add the LibraryManager tool using a command provided from the ASP.Net SignalR tutorial on a fresh install of .NET 5.0. This issue seems to only happen on my Windows machine, but I tried it with a Mac and I was able to install the tool specifically.

(Coming from this [issue](https://github.com/dotnet/AspNetCore.Docs/issues/23502) in the AspNetCore.Docs repo.)

### To Reproduce
1. Using .NET 5.0 on Windows 10 21H1
2. Run command `dotnet tool install -g Microsoft.Web.LibraryManager.Cli`
3. Command fails with the below error:
![image](https://user-images.githubusercontent.com/19719602/136872247-cdb8e30d-8c77-4d8e-8499-443cef6a1c96.png)

### Expected behavior
Expects LibraryManager to install successfully.

### Screenshots
![image](https://user-images.githubusercontent.com/19719602/136872264-311f062f-10b3-4467-862e-897b6c9b1284.png)

```
PS C:\Users\branw\Projects\SignalRChat> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.401
 Commit:    4bef5f3dbf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.401\

Host (useful for support):
  Version: 5.0.10
  Commit:  e1825b4928

.NET SDKs installed:
  5.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

cc: @guardrex

**Comment by jimmylewis** [comment]
Like in the original issue on aspnetcore.docs, I get a clean install on my machine.  Unfortunately, I'll have to redirect you again to the [dotnet SDK](https://github.com/dotnet/sdk) team for more help, the tool itself (or the Nuget package) doesn't have any control up to the point of failure.

**Comment by bdubose** [comment]
I finally found something that worked -- apparently there was some cache that was left over and causing these issues. The cache wasn't wiped away when I uninstalled/reinstalled dotnet, so that's why my problems kept persisting and was only on this computer. I believe the cache I needed to remove was somewhere under the AppData directory.
