### ISSUE TITLE
Microsoft.Web.LibraryManager.Build.targets references netstandard1.3 of Microsoft.Web.LibraryManager.dll

### ISSUE THREAD

**Issue by jenscski** [aspnet/LibraryManager#66]
The Microsoft.Web.LibraryManager.Build.targets tries to use a netstandard1.3 version of the Microsoft.Web.LibraryManager.dll

```
 <_LibraryTaskAssembly Condition="'$(MSBuildRuntimeType)' == 'Core'">..\tools\netstandard1.3\Microsoft.Web.LibraryManager.Build.dll</_LibraryTaskAssembly>
```

But only netstandard1.5 is available.

This makes building project using dotnet cli crash.

**Comment by raquelsa** [comment]
Thanks for reporting the issue! It is a know issue and I will be sending a pull request for it soon.

**Comment by nickalbrecht** [comment]
Manually updating the target file located in `C:\Users\[username]\.nuget\packages\microsoft.web.librarymanager.build\1.0.20\build` to be `netstandard1.5` instead will fix it as a work-around until an updated version of the build package is published.

**Comment by ptupitsyn** [comment]
Any update on this? ETA for the new release with the fix? Maybe nightly build?

I would really like to use this in .NET Core project. Fixing a file in nuget cache is not an option for CI and team environment.

**Comment by hajekj** [comment]
I second this, maybe add a nightly build to MyGet?

**Comment by hajekj** [comment]
And just btw, you can get the built libraries from here: https://ci.appveyor.com/project/aspnetci/librarymanager/branch/master/artifacts

**Comment by jenscski** [comment]
Looks like current version on https://www.nuget.org/ works now.
