### ISSUE TITLE
"libman.json@1.10.0" library could not be resolved

### ISSUE THREAD

**Issue by VahidN** [aspnet/LibraryManager#721]
After running the `libman restore` command, I'm getting this error message
```
[LIB002]: The "libman.json@1.10.0" library could not be resolved by the "jsdelivr" provider
```
I'm using the `2.1.175+29a28921bd.RR` version.

**Comment by jimmylewis** [comment]
What package are you expecting to find?  I don't find a "libman.json" package searching in jsdelivr or in npm (which is what jsdelivr mirrors)

**Comment by VahidN** [comment]
I'm looking for bootstrap and bootstarp-icons.

**Comment by jimmylewis** [comment]
So your libman.json file should look something like this:
```
{
  "version": "1.0",
  "defaultProvider": "jsdelivr",
  "libraries": [
    {
      "library": "bootstrap@5.3.2",
      "destination": "wwwroot/lib/bootstrap"
    },
    {
      "library": "bootstrap-icons@1.11.1",
      "destination": "wwwroot/lib/bootstrap-icons"
    }
  ]
}
```
Is that similar to what you had?  Or what did yours look like when you got this error?

**Comment by VahidN** [comment]
Yes, exactly. It's the same and i tried different `defaultProvider`s as well.

**Comment by jimmylewis** [comment]
Weird, I can't reproduce this with either the libman CLI tool or with Visual Studio.  Can you share the contents of you libman.json file?  I noticed in the Fiddler screenshot that it's using unpkg instead of jsdelivr as in the original error, so I just wanted to double check everything...

**Comment by VahidN** [comment]
I'm very sorry. That was my fault.

**Comment by asgharb** [comment]
I think it was solved. It should have been run in PowerShell. Finally, it gave the message (Build succeeded).
