### ISSUE TITLE
Discussion: LibMan CLI

### ISSUE THREAD

**Issue by justcla** [aspnet/LibraryManager#77]
We are producing a CLI for LibMan. This is the current design for the v1 prototype.
Does this capture your needs?
Please respond with any suggestions or other relevant feedback.

**Verb/Attribute** | **Description** | **Examples**
-- | -- | --
--version | Print the   current version of the LibMan executable. | Libman --version
--help   (-h) | Print a list of all available LibMan verbs.<br>If parameter supplied, will print the full details of the supplied verb. (maybe not) | Libman   --help   <br>Libman -h
Init | Creates new libman.json in the current directory.<br><br>Interactive:<br>If the user calls “libman init” with no parameters, LibMan will enter interactive   mode and prompt the user to supply a defaultProvider and defaultDestination.<br>The   default presented to the user for defaultProvider will be “cdnjs”.<br>The   default presented to the user for defaultDestination will be “libman”. <br>If the   user specifies either defaultProvider or defaultDestination, there will be no   interactive prompting for the other default option.<br><br><br>Flow:<br>User calls   **init**, then edits the content in an editor.   <br>User calls   **init**, then calls **install** to add library definitions to the   libman.json.<br>       <ul><li>“Libman init”</li><li>Prompted for defaultProvider and defaultDestination.   Accept defaults or change. </li><li>“Libman install jquery”   </li><li>Installs jquery@3.2.1 with default   provider into default destination   <br>o (Note: “jquery@[version]") is a cdnjs-specific identifier)</li></ul><br>Another   flow:<ul><li>Libman init –defaultDestination scripts</li><li>Libman install jquery@3.2.1</li><li>User is prompted for provider (default “cdnjs”). After   entering provider, user is prompted to save this as the defaultProvider.</li></ul>     Error if   libman.json already exists. | libman   init<br>(interactive:   will prompt for default provider and default destination)<br><br>libman   init --defaultProvider  "cdnjs"<br>   (non-interactive:   will not specify default destination)<br><br>libman   init --defaultProvider cdnjs --defaultDestination script\libman<br>   (non-interactive)
Install | Adds the   specified library to the libman.json, and downloads the file/s to the   specified destination.<br><br>Files   attribute must always be last.<br><br>Will   initialize a libman.json if one does not exist.<br><br>Will error   if provider is not specified and no default provider exists.<br>Will error   if destination is not specified and no default destination exists.<br>If no   files are specified, the entire library is included.<br><br>For CDNJS libraries, if no version is   specified with the library ID, the highest version available is used.<br><br>Install can be used to upgrade or downgrade   a given library.<br><br>If a   version of the library being installed already exists, fail – unless “Force”   flag specified. Then will update the specified library, removing any redundant   files from the previous version. | libman   install jquery<br>(error if   no default provider or destination)<br><br>libman   install jquery@3.2.1jquery@3.2.1<br>(this   assumes jquery@version is a valid identifier for the defaultProvider, or else   will throw an error)<br><br>libman   install jquery --provider cdnjs<br><br>libman   install jquery --files "jquery.min.js"   "jquery.min.js.map"       <br><br>libman   install jquery --destination "scripts/jquery"       <br><nobr>libman install jquery --provider cdnjs   --destination "scripts/jquery" --files "jquery.min.js"</nobr>       <br>libman   install jquery@1.1.1 -f
Uninstall | Delete the   library file/s from the specified destination, then remove the specified   library config from libman.json.<br><br>Error if   not exactly one library found. | libman   uninstall jquery<br><br>libman   uninstall jquery@3.2.1<br><br>libman   uninstall jquery --provider cdnjs
Restore | Downloads   all files from provider and saves them to configured destination.<br><br>Error if   no libman.json in folder. | libman   restore
Update | Updates (upgrades) the specified   library (or all libraries if none specified) to the latest version.<br><br>       "-pre" flag used to fetch latest   pre-release version<br><br>Will fail if specified library   doesn't exist.<br><br>Note: To specify a specific   version, use Install. | libman update<br><br>libman update jquery<br><br>libman update --provider cdnjs<br><br>libman update jquery@3.2.1<br><br>libman update jquery --provider   cdnjs<br><br>libman update jquery -pre
Clean | Delete   from the local project all library files defined in libman.json.<br><br>Delete any   folders that become empty after this operation. | libman   clean
Cache List | Print a   list of all libraries that are stored in the local machine’s LibMan cache. | libman   cache list
Cache   Clean | Delete all   files from the local machine's LibMan cache. | libman   cache clean

**Switches available on all commands**

**Verb/Attribute** | **Description** | **Examples**
-- | -- | --
--help   (-h) | Provides   printed help output for the given verb. | libman   install –help<br><br>libman   restore -h<br><br>libman   cache -h
--verbosity (-v) |   |  
--quiet (-q) |   |  

**Other root options to consider**
--force
--non-interactive

**LibMan Cache**

LibMan will maintain a cache of all libraries downloaded in the user’s home directory (ie. C:\Users\[username]\.libman\cache)<br>The libraries will be organized in folders by Provider, then provider-specific library ID.<br>The root of the LibMan cache can contain a settings file where machine-global settings can be defined.<br>Here’s an example:<br>
![image](https://user-images.githubusercontent.com/17131343/39553854-74e48dc6-4e24-11e8-814e-c30f21cfcdd5.png)

**Comment by mikaelsnavy** [comment]
Little late to the party here @justcla but just spent a good amount of time looking at this and it looks great! I'm a libman user, it fits my use cases great and have been wanting a cli for it. 

One suggestion, how about the "-pre" switch on install? Use case is if a developer is installing packages through the cli and wants the pre-release from the start.

**Comment by MorenoGentili** [comment]
Excuse me, how do I search for packages from the command line? Do I actually need to visit the provider website? Maybe it could work like `apt` or `yum`, like:
```
libman search whatever
```

**Comment by jimmylewis** [comment]
Closing this item as the CLI package has long since shipped: https://www.nuget.org/packages/Microsoft.Web.LibraryManager.Cli/
