### ISSUE TITLE
Discussion: Optional "alias" property in library definition

### ISSUE THREAD

**Issue by justcla** [aspnet/LibraryManager#82]
Given that the same library might be defined multiple times in libman.json (i.e. for different file placements, or different library versions), we need some way to identify a specific library definition when using the command line to perform an uninstall or update command.

One solution we've devised to solve this is to introduce an optional "alias" property in the library definition to disambiguate blocks that reference the same library.

This is only of use in the command line scenario; it is redundant when editing the libman.json as the user can easily see which library block to modify.

**Technical notes:**
When installing a library, the provider will be asked for the real/full version of the library name.
If I ask CDNJS to install "jquery", it can return "jquery@3.3.1" as the resolved version of that short-name.
In the case where the real/full name is different to the short-name used on the command line, the short-name will be inserted as an alias in the library definition.
Then, when the use wants to update or uninstall that library definition, then can (and must) refer to the block by its alias "jquery", instead of the full name "jquery@3.3.1".
Separately, a user can force an alias by providing the --alias flag. In that case, the provided alias will be used, regardless of whether the short-name matched the real-name.

**Example usage from the command line:**

`libman install jquery`

produces the following library definition block:

<pre>
  {
    "alias": "jquery",
    "library": "jquery@3.3.1"
  },
</pre>

In this instance, LibMan creates the alias "jquery" because the full library name returned from the provider is different to the input library name and no other alias was specified.

To update or uninstall this block from the command line, the alias must be used.

`libman update jquery`
`libman update jquery --to jquery@3.4.0`
`libman uninstall jquery`

**Example with --alias flag:**

`libman install jquery --alias latest-jquery`

produces the following library definition block:

<pre>
  {
    "alias": "latest-jquery",
    "library": "jquery@3.3.1"
  },
</pre>

To update or uninstall this block from the command line, the alias must be used.

`libman update latest-jquery`

**Example with no alias:**

libman install jquery@3.3.1

produces the following library definition block:

<pre>
  {
    "library": "jquery@3.3.1"
  },
</pre>

To update or uninstall this block from the command line, the full library name must be used.

`libman uninstall jquery@3.3.1`

**Comment by jimmylewis** [comment]
We decided not to implement this feature at this time.
